version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.db_env
  web:
    build: ./web
    command: gunicorn web.wsgi:application --bind 0.0.0.0:$PORT
    ports:
      - "$PORT:$PORT"
    env_file:
      - ./.env
    volumes:
      - ./web:/web/
    depends_on:
      - db

volumes:
  data:
  web:
